let DATA = {
    "donut": {
        "title": "the donut of knowledge",
        "image": "images/donut.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://www.youtube.com/watch?v=ohyai6GIRZg",
        "imagemap": [
            {
                name: "maths",
                class: "maths",
                shape: "poly",
                coords: "266,1239,302,1263,363,1285,438,1309,487,1319,507,1285,582,1216,587,1165,589,1117,611,1034,675,1012,704,954,670,948,670,958,438,958,407,1005,421,1041,414,1124,382,1185",
                href: "#",
                alt: "",
                color: "white",
                points_to: "maths",
            },
            {
                name: "astronomy-cosmology",
                class: "astronomy-cosmology",
                shape: "poly",
                coords: "745,1325,737,1239,715,1183,665,1155,588,1159,586,1207,505,1295,490,1316,568,1327,700,1326",
                href: "#",
                alt: "",
                color: "white",
                points_to: "the-universe",
            },
            {
                name: "chemistry",
                class: "chemistry",
                shape: "poly",
                coords: "885,970,937,1079,905,1118,895,1156,961,1205,1057,1160,1133,1168,1138,1124,1122,1076,1152,999,1117,935,1065,882,1001,837,904,873,928,920,943,924,941,971",
                href: "#",
                alt: "",
                color: "white",
                points_to: "chemistry",
            },
            {
                name: "computer-science",
                class: "computer-science",
                shape: "poly",
                coords: "620,670,704,689,775,697,827,699,826,784,808,800,774,846,763,892,716,921,706,950,670,948,670,918,438,920,438,886,419,729,601,707",
                href: "#",
                alt: "",
                color: "white",
                points_to: "computer-science",
            },
            {
                name: "physics",
                class: "physics",
                shape: "poly",
                coords: "612,1035,675,1015,707,954,719,957,719,969,884,970,936,1082,904,1115,899,1142,892,1154,850,1198,741,1242,714,1183,668,1155,589,1159,589,1128",
                href: "#",
                alt: "",
                color: "white",
                points_to: "physics",
            },
            {
                name: "engineering",
                class: "engineering",
                shape: "poly",
                coords: "1162,677,1209,722,1299,722,1303,765,1274,765,1304,783,1359,722,1391,717,1391,641,1374,600,1279,590,1225,599,1199,649,1199,666",
                href: "#",
                alt: "",
                color: "white",
                points_to: "engineering",
            },
            {
                name: "biology",
                class: "biology",
                shape: "rect",
                coords: "1325,1060,1491,1107",
                href: "#",
                alt: "",
                color: "white",
                points_to: "biology",
            },
            {
                name: "philosophy",
                class: "philosophy",
                shape: "poly",
                coords: "29,724,183,717,304,717,416,733,441,890,438,919,436,962,404,1004,417,1041,414,1125,378,1187,261,1240,178,1192,107,1119,64,1048,46,997,31,870",
                href: "#",
                alt: "",
                color: "white",
                points_to: "philosophy",
            },
            {
                name: "doom",
                class: "doom",
                shape: "rect",
                coords: "1918,1350,1905,1336",
                href: "#",
                alt: "",
                color: "white",
                points_to: "doom",
            },
            {
                name: "",
                class: "",
                shape: "poly",
                coords: "",
                href: "#",
                alt: "",
                color: "white",
            },
        ]
    },
    "maths": {
        "title": "the map of maths",
        "image": "images/math.png",        
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://www.youtube.com/watch?v=OmJ-4B-mS-Y",
        "imagemap": [
            {
                name: "mathematical chemistry",
                class: "mathematical-chemistry",
                shape: "rect",
                coords: "1394,1045,1603,1091",
                href: "#",
                alt: "",
                color: "white",
                points_to: "chemistry",
            },
            {
                name: "biomathematics",
                class: "biomathematics",
                shape: "rect",
                coords: "1667,1182,1864,1206",href: "#",
                alt: "",
                color: "white",
                points_to: "biology",
            },
            {
                name: "engineering",
                class: "engineering",
                shape: "rect",
                coords: "1684,924,1857,950",
                href: "#",
                alt: "",
                color: "white",
                points_to: "engineering",
            },
            {
                name: "computer science",
                class: "computer-science",
                shape: "rect",
                coords: "1430,184,1576,233",
                href: "#",
                alt: "",
                color: "white",
                points_to: "computer-science",
            },
            {
                name: "theory of computation",
                class: "computer-science",
                shape: "rect",
                coords: "383,196,536,239",
                href: "#",
                alt: "",
                color: "white",
                points_to: "computer-science",
            },
        ]
    },
    "physics": {
        "title": "the map of physics",
        "image": "images/physics.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://www.youtube.com/watch?v=gAFAj3pzvAA",
        "imagemap": [
            {
                name: "standard model",
                class: "fundamental-particles",
                shape: "rect",
                coords: "1220,601,1450,628",
                href: "#",
                alt: "",
                color: "white",
                points_to: "fundamental-particles",
            },
            {
                name: "particle physics",
                class: "fundamental-particles",
                shape: "rect",
                coords: "1488,1003,1727,1038",
                href: "#",
                alt: "",
                color: "white",
                points_to: "fundamental-particles",
            },
            {
                name: "quantum gravity",
                class: "quantum gravity",
                shape: "rect",
                coords: "1647,421,1893,453",
                href: "#",
                alt: "",
                color: "white",
                points_to: "quantum-gravity",
            },
            {
                name: "computers",
                class: "computers",
                shape: "rect",
                coords: "658,1016,762,1047",
                href: "#",
                alt: "",
                color: "white",
                points_to: "computer-science",
            },
            {
                name: "calculus",
                class: "calculus",
                shape: "poly",
                coords: "309,395,292,404,224,410,98,409,2,414,2,193,46,202,41,219,37,237,48,253,76,261,103,258,119,232,200,319",
                href: "#",
                alt: "",
                color: "white",
                points_to: "maths"
            },
            {
                name: "quantum physics",
                class: "quantum-physics",
                shape: "rect",
                coords: "870,961,1465,1036",
                href: "#",
                alt: "",
                color: "white",
                points_to: "quantum-physics",
            },
            {
                name: "philosophy",
                class: "philosophy",
                shape: "poly",
                coords: "1338,2,1320,24,1316,47,1333,61,1345,71,1333,81,1330,91,1308,112,1304,139,1320,158,1352,171,1367,175,1369,188,1386,198,1352,208,1389,214,1437,212,1484,208,1465,220,1572,225,1535,244,1525,249,1540,256,1582,258,1635,264,1701,256,1764,256,1789,256,1822,247,1817,234,1844,230,1837,219,1864,220,1895,212,1908,203,1917,207,1913,0",
                href: "#",
                alt: "",
                color: "white",
                points_to: "philosophy",
            },
            {
                name: "optics",
                class: "optics",
                shape: "rect",
                coords: "424,390,509,416",
                href: "#",
                alt: "",
                color: "white",
                points_to: "atomic-spectra",
            },
            {
                name: "si units",
                class: "si-units",
                shape: "circle",
                coords: "384,102,30",
                href: "#",
                alt: "SI Units",
                color: "white",
                points_to: "si-units",
            }

        ]
    },
    "engineering": {
        "title": "the map of engineering",
        "image": "images/engineering.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://www.youtube.com/watch?v=pQgxiQAMTTo",
        "imagemap": [
            {
                name: "computer engineering",
                class: "computer-engineering",
                shape: "rect",
                coords: "1774,1359,1959,1417",
                href: "#",
                alt: "",
                color: "white",
                points_to: "computer-science",
            },
            {
                name: "chemical engineering",
                class: "chemical-engineering",
                shape: "rect",
                coords: "69,1324,237,1380",
                href: "#",
                alt: "",
                color: "white",
                points_to: "chemistry",
            },
            {
                name: "bio engineering",
                class: "bio-engineering",
                shape: "rect",
                coords: "903,1548,1070,1606",
                href: "#",
                alt: "",
                color: "white",
                points_to: "biology",
            },
        ]
    },
    "computer-science": {
        "title": "the map of computer science",
        "image": "images/computer-science.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://youtu.be/SzJ46YA_RaA",
        "imagemap": [
            {
                name: "quantum computing",
                class: "quantum-computing",
                shape: "rect",
                coords: "721,613,838,641",
                href: "#",
                alt: "",
                color: "white",
                points_to: "quantum-computing",
            },
            
        ]
    },
    "quantum-computing": {
        "title": "the map of quantum computing",
        "image": "images/quantum-computing.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://www.youtube.com/watch?v=-UlxHPIEVqA",
        "imagemap": []
    },
    "chemistry": {
        "title": "the map of chemistry",
        "image": "images/chemistry.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://youtu.be/P3RXtoYCW4M",
        "imagemap": [
            {
                name: "physics",
                class: "physics",
                shape: "poly",
                coords: "1376,1314,1562,1294,1564,1321,1396,1346",
                href: "#",
                alt: "",
                color: "white",
                points_to: "physics",
            },
            {
                name: "computational chemistry",
                class: "computational-chemistry",
                shape: "poly",
                coords: "1538,1030,1693,1030,1691,1074,1557,1077",
                href: "#",
                alt: "",
                color: "white",
                points_to: "chemistry",
            },
            {
                name: "molecular biology",
                class: "molecular-biology",
                shape: "poly",
                coords: "1795,191,1913,191,1917,240,1898,289,1840,286,1788,218",
                href: "#",
                alt: "",
                color: "white",
                points_to: "biology",
            },
        ]
    },
    "biology": {
        "title": "the map of biology",
        "image": "images/biology.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://youtu.be/wENhHnJI1ys",
        "imagemap": [
            {
                name: "the chain of life",
                class: "the-chain-of-life",
                shape: "poly",
                coords: "701,502,736,489,977,486,1075,460,1072,229,678,226,668,443,702,455",
                href: "#",
                alt: "",
                color: "white",
                points_to: "chain-of-life",
            },
            {
                name: "virus",
                class: "virus",
                shape: "rect",
                coords: "808,1091,855,1115",
                href: "#",
                alt: "",
                color: "white",
                points_to: "virus",
            },
        ]
    },
    "quantum-physics": {
        "title": "the map of quantum physics",
        "image": "images/quantum-physics.jpg",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://youtu.be/gAFAj3pzvAA",
        "imagemap": [
            {
                name: "quantum gravity",
                class: "quantum-gravity",
                shape: "rect",
                coords: "1671,148,1847,172",
                href: "#",
                alt: "",
                color: "white",
                points_to: "quantum-gravity",
            },
            {
                name: "quantum chemistry",
                class: "quantum-chemistry",
                shape: "rect",
                coords: "1320,1218,1499,1242",
                href: "#",
                alt: "",
                color: "white",
                points_to: "chemistry",
            },
            {
                name: "quantum biology",
                class: "quantum-biology",
                shape: "rect",
                coords: "782,1081,964,1109",
                href: "#",
                alt: "",
                color: "white",
                points_to: "biology",
            },
            {
                name: "quantum computing",
                class: "quantum-computing",
                shape: "rect",
                coords: "1160,774,1261,810",
                href: "#",
                alt: "",
                color: "white",
                points_to: "quantum-computing",
            },
            {
                name: "quantum simulation",
                class: "quantum-simulation",
                shape: "poly",
                coords: "1272,797,1245,838,1362,838,1350,797",
                href: "#",
                alt: "",
                color: "white",
                points_to: "quantum-simulation",
            },
            {
                name: "quantum gravity",
                class: "quantum-gravity",
                shape: "rect",
                coords: "1667,146,1847,171",
                href: "#",
                alt: "",
                color: "white",
                points_to: "quantum-gravity",
            },
            {
                name: "quantum nose",
                class: "quantum-nose",
                shape: "poly",
                coords: "750,1242,857,1242,841,1308,845,1391,812,1415,772,1391",
                href: "#",
                alt: "",
                color: "white",
                points_to: "quantum-nose",
            },
            {
                name: "superconductivity",
                class: "superconductivity",
                shape: "rect",
                coords: "34,927,229,1022",
                href: "#",
                alt: "",
                color: "white",
                points_to: "superconductivity",
            },
            {
                name: "feynman diagrams",
                class: "not-yet",
                shape: "poly",
                coords: "1387,804,1403,868,1403,918,1532,926,1535,877,1554,826,1549,795",
                href: "#",
                alt: "",
                color: "white",
                points_to: "feynman-diagrams",
            },
            {
                name: "standard model",
                class: "standard-model",
                shape: "rect",
                coords: "1559,798,1896,829",
                href: "#",
                alt: "",
                color: "white",
                points_to: "fundamental-particles",
            },
            {
                name: "nuclear physics",
                class: "nuclear-physics",
                shape: "rect",
                coords: "1688,1078,1850,1103",
                href: "#",
                alt: "",
                color: "white",
                points_to: "physics",
            },
            {
                name: "atomics spectra",
                class: "atomics-spectra",
                shape: "rect",
                coords: "56,185,204,260",
                href: "#",
                alt: "",
                color: "white",
                points_to: "atomics-spectra",
            },

        ]
    },
    "quantum-gravity": {
        "title": "the map of quantum gravity",
        "image": "images/quantum-gravity.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://www.youtube.com/watch?v=d-86tNCSJsg",
        "imagemap": [
            {
                name: "black holes",
                class: "black-holes",
                shape: "rect",
                coords: "1159,275,1310,386",
                href: "#",
                alt: "",
                color: "white",
                points_to: "black-holes",
            },
            {
                name: "black holes",
                class: "black-holes",
                shape: "rect",
                coords: "980,686,1115,792",
                href: "#",
                alt: "",
                color: "white",
                points_to: "black-holes",
            },
        ]
    },
    "fundamental-particles": {
        "title": "the map of fundamental particles",
        "image": "images/fundamental-particles.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://youtu.be/mYcLuWHzfmE",
        "imagemap": [
            {
                name: "can you see neutrinos",
                class: "can-you-see-neutrinos-with-eyes",
                shape: "rect",
                coords: "219,861,342,837",
                href: "#",
                alt: "",
                color: "white",
                points_to: "can-you-see-neutrinos-with-eyes",
            }
        ]
    },
    "philosophy": {
        "title": "the map of philosophy",
        "image": "images/philosophy.png",
        "author_name": "Carneades",
        "author_link": "https://www.carneades.org/",
        "youtube_video": "https://www.youtube.com/watch?v=YxBShJU_CKs",
        "imagemap": []
    },
    "chain-of-life": {
        "title": "the chain of life",
        "image": "images/chain-of-life.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://www.youtube.com/watch?v=GRm__SOzz6c",
        "imagemap": []
    },
    "black-holes": {
        "title": "the map of black holes",
        "image": "images/black-holes.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://www.youtube.com/watch?v=Wf0uxjWGwPk",
        "imagemap": [
            {
                name: "gravitational waves",
                class: "gravitational-waves",
                shape: "poly",
                coords: "1012,1324,1402,1324,1383,1357,1387,1641,953,1641,951,1409",
                href: "#",
                alt: "",
                color: "white",
                points_to: "gravitational-waves",
            }
        ]
    },
    "plastics": {
        "title": "things-to-do-with-plastics",
        "image": "images/plastics.jpg",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://www.youtube.com/watch?v=bL7WvdNdk3Y",
        "imagemap": [
            
        ]
    },
    "superconductivity": {
        "title": "the map of superconductivity",
        "image": "images/superconductivity.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://www.youtube.com/watch?v=bD2M7P6dTVA",
        "imagemap": []
    },
    "doom": {
        "title": "the map of doom",
        "image": "images/doom.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://www.youtube.com/watch?v=Htf0XR6W9WQ",
        "imagemap": []
    },
    "atomic-spectroscopy": {
        "title": "atomic spectroscopy",
        "image": "images/atomic-spectra.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://youtu.be/crWBFuUW6kI",
        "imagemap": []
    },
    "virus": {
        "title": "the map of viruses",
        "image": "images/virus.jpg",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://youtu.be/754YnbOtmvA",
        "imagemap": []
    },
    "the-universe": {
        "title": "The universe",
        "image": "images/the-universe.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://www.youtube.com/watch?v=uniGQrGLEoI",
        "imagemap": [
            {
                name: "black holes",
                class: "black-holes",
                shape: "circle",
                coords: "698,442,18",
                href: "#",
                alt: "",
                color: "white",
                points_to: "black-holes",
            },
            {
                name: "black holes",
                class: "black-holes",
                shape: "poly",
                coords: "937,128,936,147,948,159,956,179,979,188,996,182,998,159,1022,147,1023,131",
                href: "#",
                alt: "",
                color: "white",
                points_to: "black-holes",
            },
            {
                name: "big bang",
                class: "big-bang",
                shape: "poly",
                coords: "1384,62,1405,66,1415,127,1392,140",
                href: "#",
                alt: "",
                color: "white",
                points_to: "big-bang",
            },
        ]
    },
    "gravitational-waves": {
        "title": "gravitational waves",
        "image": "images/gravitational-wave-astronomy.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://www.youtube.com/watch?v=AFhOzhe9mg4",
        "imagemap": [
            {
                name: "black holes",
                class: "black-holes",
                shape: "circle",
                coords: "264,206,29",
                href: "#",
                alt: "",
                color: "white",
                points_to: "black-holes",
            },
            {
                name: "black holes",
                class: "black-holes",
                shape: "circle",
                coords: "298,142,23",
                href: "#",
                alt: "",
                color: "white",
                points_to: "black-holes",
            },
        ]
    },
    "big-bang": {
        "title": "the map of big-bang",
        "image": "images/big-bang.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://youtu.be/P1Q8tS-9hYo",
        "imagemap": []
    },
    "quantum-nose": {
        "title": "your quantum nose",
        "image": "images/your-quantum-nose.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://youtu.be/DJsJIVXkrGQ",
        "imagemap": []
    },
    "the-state-of-quantum-computing-jan-2022": {
        "title": "The State of Quantum Computing Jan 2022",
        "image": "images/the-state-of-quantum-computing-jan-2022.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://youtu.be/gcbMKt079l8",
        "imagemap": []
    },
    "can-you-see-neutrinos-with-eyes": {
        "title": "can-you-see-neutrinos-with-eyes",
        "image": "images/can-you-see-neutrinos-with-eyes.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "",
        "imagemap": [
            {
                name: "standard model",
                class: "standard-model",
                shape: "rect",
                coords: "755,232,244,132",
                href: "#",
                alt: "",
                color: "white",
                points_to: "fundamental-particles",
            },
        ]
    },
    "quantum-simulation": {
        "title": "quantum simulation",
        "image": "images/quantum-simulation.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://youtu.be/kD370qyxTyw",
        "imagemap": [
            {
                name: "chemistry",
                class: "chemistry",
                shape: "rect",
                coords: "2259,693,2429,748",
                href: "#",
                alt: "",
                color: "white",
                points_to: "chemistry",
            },
            {
                name: "the state of quantum computing",
                class: "the-state-of-quantum-computing",
                shape: "rect",
                coords: "1733,1513,1950,1580",
                href: "#",
                alt: "",
                color: "white",
                points_to: "the-state-of-quantum-computing-jan-2022",
            },
            {
                name: "superconductivity",
                class: "superconductivity",
                shape: "rect",
                coords: "1067,205,1394,254",
                href: "#",
                alt: "",
                color: "white",
                points_to: "superconductivity",
            },
        ]
    },
    "si-units": {
        "title": "SI Units",
        "image": "images/SI-Units.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "https://youtu.be/aYIbC25GNKs",
        "imagemap": []
    },
    "": {
        "title": "",
        "image": "images/.png",
        "author_name": "Dominic Walliman",
        "author_link": "https://dominicwalliman.com/",
        "youtube_video": "",
        "imagemap": []
    }




}

